### ISSUE TITLE
Addition of RFTools.

### ISSUE THREAD

**Issue by calmcacil** [EinherjarMC/Einherjar-Dev#2]
Addition of RFTools is currently on hold until i have looked into balancing the mod somewhat.

**Comment by compwiz1548** [comment]
Balance Suggestions:
-Make certain dimlets more rare (i.e. yellorium, iron, etc.)
-Increase power drain (perhaps by 10)

**Comment by compwiz1548** [comment]
Possibly balanced by the removal of Big Reactors (maybe)
